version: 0.0.1
language: nodejs
nodejs_version: "8"
pipeline_os: "Linux"
env:  
  - buildArgs: ${DOCKER_ARGS} BUILD_NAME=${DOCKER_TAG}

build:
  scripts:        
    - "${buildArgs}"
    - `${buildArgs}`

test:
  ulr: "{{env.buildArgs}}"
  url2: "{{buildArgs}}"
  