version: 0.0.1
language: nodejs
nodejs_version: "8"
pipeline_os: "Linux"
buildArgs: 'npm install'
env:  
  - buildArgs: "npm --v"

build:
  scripts:        
    - "./jenkins/scripts/kill.sh"

test:
  ulr: $env.buildArgs
  url2: "$env.buildArgs"
  