version: 0.0.1
language: nodejs
nodejs_version: "8"
pipeline_os: "Linux"
buildArgs: 'npm install'
env:  
  - buildArgs: $BUILD_NUMBER

build:
  scripts:        
    - "./jenkins/scripts/kill.sh"

test:
  ulr: $buildArgs
  url2: $BUILD_NUMBER
  