version: 0.0.1
language: nodejs
nodejs_version: "8"
pipeline_os: "Linux"
env:
  - DOCKER_ORG: artifactory.dev.adskengineer.net/autodeskcloud
  - DOCKER_REGISTRY: https://artifactory.dev.adskengineer.net/artifactory/docker-local-v2/
  - DOCKER_CREDENTIALS: artifactory-deploy-dev
  - NODE_IMAGE: artifactory.dev.adskengineer.net/quantum-devops/cloudos-v2/base-nodejs8:latest
  - BUILD_VERSION: 0.0.${BUILD_NUMBER}
  - SAFE_BRANCH_NAME: BRANCH_NAME.replaceAll('/','-')
  - DOCKER_TAG: SAFE_BRANCH_NAME + "-${BUILD_VERSION}"
  - DOCKER_ARGS: DOCKER_ORG=${DOCKER_ORG} DOCKER_TAG=${DOCKER_TAG}
  - currentBuild.displayName : DOCKER_TAG   
  - buildArgs: ${DOCKER_ARGS} BUILD_NAME=${DOCKER_TAG}

build:
  scripts:
    - "npm install"
    - "node --version"